### ISSUE TITLE
WSL Ubuntu Bash is required

### ISSUE THREAD

**Issue by yorek** [morsh/social-posts-pipeline#12] opened 2018-10-04 21:42 UTC
I suggest to mention in the "requirements" that script must be run from an Ubuntu Bash (using WSL is ok), otherwise you won't have make tool available. Otherwise make should be listed as a required tool

**Comment by morsh** [comment] 2018-10-09 21:19
@yorek - good suggestion, I'll update it soon, or you can PR it :)

**Comment by morsh** [comment] 2018-11-12 11:44
@yorek - this was fixed in the main README file, so the issue is closed

**Closed** 2018-11-12 11:44 UTC
Labels: enhancement
